### PR TITLE
Fix malformed config.json + Add Adjust ease factors of all decks feature

### PR DESCRIPTION
**Pull request by RisingOrange**
Hey @brownbat , I found the reason for the config being inaccessible. There was closing bracket missing in the config.json file.

### CODE REVIEW

**Comment by RisingOrange** [comment]
I also added the "Adjust ease factors of all decks" option. I implemented it so that it runs when a user profile gets closed instead on startup. When I developed the ResetEaseAutomatically add-on I initially had it it adjust the ease factors on startup, but it did it before the synch from AnkiWeb and this messed up some things. There probably is a way how to adjust the ease factors safely on startup, but adjusting them when closing the profile worked without problems in my case, so why not just do it this way.

**Comment by Willz7** [comment]
Hi @RisingOrange, thank you for implementing the "Adjust ease factors of all decks" option on Auto Ease Factor. I tried to use your version to see if it works on Anki 2.1.22 I got this error `  Caught exception:
Traceback (most recent call last):
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 308, in adjust_all_decks
    for x in mw.col.decks.all_names_and_ids():
AttributeError: 'DeckManager' object has no attribute 'all_names_and_ids'
 `

**Comment by SuatBabatan** [comment]
I downloaded your fork and it worked. thanks .
I am using 2.1.42

@Willz7  I belive why yours is not worked is that deck option patch in @brownbat 's version is for 2.1.40 and above
